### PR TITLE
Schema refresh

### PR DESCRIPTION
**Pull request by ikeyd**
Please see individual commits for rationale

 - Use meson scripting instead of mixing bash scripting to ensure consistency in restricted build environments
 - Add sane touchpad defaults for laptop users
 - Enable GTK/Shell animations again (See commit for details)

### CODE REVIEW

**Comment by mrkz** [comment]
Thanks for the pull request!

Overall it looks good, I'm just merging this, but if we do animations back by default, would be nice to get them 2x the default speed as well, maybe other gschema override should be enough?

**Comment by mrkz** [comment]
we could also ship [impatience extension](https://github.com/timbertson/gnome-shell-impatience) with a `0.5` setup

**Comment by ikeyd** [comment]
Definitely ship impatience to speed up gnome shell :)

**Comment by mrkz** [comment]
@ikeyd I've drafted a new release (V16) with these changes, except for the `Enable GTK animations by default once more`. I'd like to integrate impatience extension prior to enabling this back.

**Comment by ikeyd** [comment]
Sure - once things are flowing correctly I'll pop impatience extension into a package

**Pull request merged**
